# Generated by Django 3.0.8 on 2020-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_category_one_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='one_size',
        ),
        migrations.AddField(
            model_name='product',
            name='one_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceLarge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
    ]
