# Generated by Django 3.0.8 on 2020-07-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200717_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='topping_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('O', 'One Size '), ('L', 'Large')], max_length=1),
        ),
    ]
