# Generated by Django 3.0.8 on 2020-07-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200717_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_allowed_additional',
            field=models.BooleanField(default=False),
        ),
    ]
