# Generated by Django 3.0.8 on 2020-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_product_is_allowed_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='additional',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Additional'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='additional_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Topping'),
        ),
    ]
