# Generated by Django 3.0.8 on 2020-07-18 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_auto_20200718_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('additional_quantity', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('O', 'One Size '), ('L', 'Large')], max_length=1)),
                ('ordered', models.BooleanField(default=False)),
                ('additional', models.ManyToManyField(blank=True, null=True, to='orders.Additional')),
                ('product', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='orders.Product')),
                ('toppings', models.ManyToManyField(blank=True, null=True, to='orders.Topping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('orderTime', models.TimeField(auto_now_add=True)),
                ('orderProduct', models.ManyToManyField(to='orders.OrderProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
