# Generated by Django 3.0.8 on 2020-07-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='additional_quantity',
        ),
    ]
