# Generated by Django 3.0.8 on 2020-07-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderproduct_additional_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='additional',
            field=models.ManyToManyField(blank=True, to='orders.Additional'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
