# Generated by Django 3.0.8 on 2020-07-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
